[workspace]
members = [
    "crates/primitives",
    "crates/profile",
    "crates/ssz",
    "crates/types",
    "crates/crypto",
    "crates/genesis",
    "crates/transition",
    "crates/fork-choice",
    "crates/storage",
    "crates/network-wire",
    "crates/network",
    "crates/sync",
    "crates/validator",
    "crates/node",
    "crates/rpc",
    "crates/metrics",
    "crates/spec-fixtures",
    "bin/ethean",
    "bin/ethean-leanvm-mock",
]
resolver = "2"

[workspace.package]
version = "0.1.11"
edition = "2021"
license = "MIT"
authors = ["Ethean contributors"]
repository = "https://github.com/Pamenarti/Ethean"

[workspace.dependencies]
ethean-primitives = { path = "crates/primitives" }
ethean-profile = { path = "crates/profile" }
ethean-ssz = { path = "crates/ssz" }
ethean-types = { path = "crates/types" }
ethean-crypto = { path = "crates/crypto" }
ethean-genesis = { path = "crates/genesis" }
ethean-transition = { path = "crates/transition" }
ethean-fork-choice = { path = "crates/fork-choice" }
ethean-storage = { path = "crates/storage" }
ethean-network-wire = { path = "crates/network-wire" }
ethean-network = { path = "crates/network" }
ethean-sync = { path = "crates/sync" }
ethean-validator = { path = "crates/validator" }
ethean-node = { path = "crates/node" }
ethean-rpc = { path = "crates/rpc" }
ethean-metrics = { path = "crates/metrics" }

tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
rocksdb = "0.21"
redb = "2.6"
futures = "0.3"
rand = "0.8"
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "ansi"] }
clap = { version = "4.0", features = ["derive"] }
tempfile = "3.8"
libp2p = { version = "0.54", default-features = false, features = ["quic", "tokio", "ping", "macros"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
debug = true
opt-level = 0
