//! Local multi-node devnet bundle: real PROD XMSS keys, a shared
//! `config.yaml`, a `validators.yaml` registry and fixed node keys, laid out
//! the way `ethean start --network <config.yaml> --validator-registry …`
//! already reads Hive / lean-quickstart bundles.
//!
//! Keys and node keys are kept across runs (PROD key generation takes tens of
//! seconds per key); only `GENESIS_TIME` changes on every write.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use ethean_crypto::SecretKeyMaterial;
use ethean_network::NodeKey;

/// Epochs each generated key covers: two PROD bottom trees, the minimum a
/// key holds, about six days of 4 s slots.
pub const KEY_ACTIVE_EPOCHS: u32 = 131_072;

/// Shape of the devnet to write.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DevnetSpec {
    pub nodes: usize,
    pub validators_per_node: usize,
    pub genesis_time: u64,
    /// QUIC port of node 0; node `k` listens on `base_port + k`.
    pub base_port: u16,
}

impl DevnetSpec {
    pub fn validator_count(&self) -> usize {
        self.nodes * self.validators_per_node
    }
}

/// Signing role of a generated key file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeyRole {
    Attestation,
    Proposal,
}

impl KeyRole {
    fn label(self) -> &'static str {
        match self {
            KeyRole::Attestation => "attestation",
            KeyRole::Proposal => "proposal",
        }
    }
}

/// One node of the written bundle.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DevnetNode {
    pub node_id: String,
    pub quic_port: u16,
    pub node_key: PathBuf,
    /// Dialable multiaddr, when the PeerId can be derived (QUIC build).
    pub multiaddr: Option<String>,
    pub validator_indices: Vec<u64>,
}

/// Paths and nodes of a written bundle.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DevnetBundle {
    pub config: PathBuf,
    pub registry: PathBuf,
    pub nodes_file: PathBuf,
    pub nodes: Vec<DevnetNode>,
    /// Key files generated by this call (the rest were reused).
    pub generated_keys: usize,
}

fn key_file_name(index: u64, role: KeyRole) -> String {
    format!("validator_{index}_{}_sk.ssz", role.label())
}

fn hex(bytes: &[u8]) -> String {
    bytes
        .iter()
        .fold(String::with_capacity(bytes.len() * 2), |mut s, b| {
            let _ = write!(s, "{b:02x}");
            s
        })
}

fn load_or_generate(
    path: &Path,
    index: u64,
    role: KeyRole,
    keygen: &mut dyn FnMut(u64, KeyRole) -> Result<SecretKeyMaterial, String>,
) -> Result<(SecretKeyMaterial, bool), String> {
    if path.is_file() {
        let bytes = fs::read(path).map_err(|e| format!("read {}: {e}", path.display()))?;
        let secret = SecretKeyMaterial::from_xmss_ssz(bytes)
            .map_err(|e| format!("decode {}: {e}", path.display()))?;
        return Ok((secret, false));
    }
    let secret = keygen(index, role)?;
    fs::write(path, secret.as_bytes()).map_err(|e| format!("write {}: {e}", path.display()))?;
    Ok((secret, true))
}

fn public_key_hex(secret: &SecretKeyMaterial) -> Result<String, String> {
    secret
        .xmss_public_key()
        .map(|pk| hex(pk.as_bytes()))
        .map_err(|e| e.to_string())
}

/// Write (or refresh) the bundle under `dir`. `keygen` is only called for key
/// files that do not exist yet.
pub fn write_bundle(
    dir: &Path,
    spec: DevnetSpec,
    keygen: &mut dyn FnMut(u64, KeyRole) -> Result<SecretKeyMaterial, String>,
) -> Result<DevnetBundle, String> {
    if spec.nodes == 0 || spec.validators_per_node == 0 {
        return Err("a devnet needs at least one node and one validator per node".into());
    }
    let last_port = u32::from(spec.base_port) + spec.nodes as u32 - 1;
    if last_port > u32::from(u16::MAX) {
        return Err(format!("ports {}..={last_port} overflow", spec.base_port));
    }
    let keys_dir = dir.join("hash-sig-keys");
    fs::create_dir_all(&keys_dir).map_err(|e| format!("create {}: {e}", keys_dir.display()))?;

    let mut generated_keys = 0;
    let mut config = format!(
        "GENESIS_TIME: {}\nNUM_VALIDATORS: {}\nGENESIS_VALIDATORS:\n",
        spec.genesis_time,
        spec.validator_count()
    );
    let mut registry = String::new();
    let mut nodes = Vec::with_capacity(spec.nodes);
    for k in 0..spec.nodes {
        let node_id = format!("ethean_{k}");
        let _ = writeln!(registry, "{node_id}:");
        let mut validator_indices = Vec::with_capacity(spec.validators_per_node);
        for v in 0..spec.validators_per_node {
            let index = (k * spec.validators_per_node + v) as u64;
            validator_indices.push(index);
            let mut pubkeys = [String::new(), String::new()];
            for (slot, role) in [KeyRole::Attestation, KeyRole::Proposal]
                .into_iter()
                .enumerate()
            {
                let file = key_file_name(index, role);
                let (secret, fresh) = load_or_generate(&keys_dir.join(&file), index, role, keygen)?;
                generated_keys += usize::from(fresh);
                pubkeys[slot] = public_key_hex(&secret)?;
                let _ = writeln!(
                    registry,
                    "  - index: {index}\n    pubkey_hex: \"{}\"\n    privkey_file: \"{file}\"",
                    pubkeys[slot]
                );
            }
            let _ = writeln!(
                config,
                "  - attestation_public_key: \"0x{}\"\n    proposal_public_key: \"0x{}\"",
                pubkeys[0], pubkeys[1]
            );
        }
        let node_key = dir.join(format!("{node_id}.key"));
        let (key, _) = NodeKey::load_or_create(&node_key)
            .map_err(|e| format!("{}: {e}", node_key.display()))?;
        let quic_port = spec.base_port + k as u16;
        let multiaddr = crate::cli_resolve::node_key_peer_id(&key)
            .map(|peer| format!("/ip4/127.0.0.1/udp/{quic_port}/quic-v1/p2p/{peer}"));
        nodes.push(DevnetNode {
            node_id,
            quic_port,
            node_key,
            multiaddr,
            validator_indices,
        });
    }

    let config_path = dir.join("config.yaml");
    let registry_path = dir.join("validators.yaml");
    let nodes_path = dir.join("nodes.yaml");
    let nodes_yaml: String = nodes
        .iter()
        .filter_map(|n| n.multiaddr.as_ref())
        .map(|m| format!("- \"{m}\"\n"))
        .collect();
    for (path, text) in [
        (&config_path, &config),
        (&registry_path, &registry),
        (&nodes_path, &nodes_yaml),
    ] {
        fs::write(path, text).map_err(|e| format!("write {}: {e}", path.display()))?;
    }
    Ok(DevnetBundle {
        config: config_path,
        registry: registry_path,
        nodes_file: nodes_path,
        nodes,
        generated_keys,
    })
}

/// Generate a PROD XMSS key covering [`KEY_ACTIVE_EPOCHS`] from genesis.
pub fn production_keygen(_index: u64, _role: KeyRole) -> Result<SecretKeyMaterial, String> {
    use ethean_crypto::{CryptoBackend, ProductionBackend};
    ProductionBackend
        .key_gen(0, KEY_ACTIVE_EPOCHS)
        .map(|(_, secret)| secret)
        .map_err(|e| e.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn vendored(index: usize, role: KeyRole) -> SecretKeyMaterial {
        let path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../crypto/testdata/xmss_test_keys")
            .join(format!("{index}.json"));
        let doc = fs::read_to_string(path).expect("vendored XMSS test key");
        let needle = format!("\"{}_secret\": \"", role.label());
        let start = doc.find(&needle).unwrap() + needle.len();
        let end = doc[start..].find('"').unwrap() + start;
        let hex = &doc[start..end];
        let bytes = (0..hex.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
            .collect();
        SecretKeyMaterial::from_xmss_ssz(bytes).unwrap()
    }

    fn spec(genesis_time: u64) -> DevnetSpec {
        DevnetSpec {
            nodes: 3,
            validators_per_node: 1,
            genesis_time,
            base_port: 9100,
        }
    }

    #[test]
    fn bundle_loads_as_genesis_and_registry_and_keeps_keys() {
        let dir = tempfile::tempdir().unwrap();
        let mut calls = 0;
        let mut keygen = |index: u64, role: KeyRole| {
            calls += 1;
            Ok(vendored(index as usize, role))
        };
        let first = write_bundle(dir.path(), spec(1_700_000_000), &mut keygen).unwrap();
        assert_eq!(first.generated_keys, 6);
        assert_eq!(first.nodes.len(), 3);
        assert_eq!(first.nodes[2].quic_port, 9102);
        assert_eq!(first.nodes[1].validator_indices, vec![1]);

        let cfg = ethean_genesis::load_lean_network_config(&first.config).unwrap();
        assert_eq!(cfg.genesis_time, 1_700_000_000);
        assert_eq!(cfg.validators.len(), 3);
        let loaded = crate::registry_keys::load_node_keys(&first.registry, "ethean_1").unwrap();
        assert_eq!(loaded.indices, vec![1]);
        let attestation = loaded.attestation.expect("attestation key");
        assert_eq!(
            attestation.public_key.as_bytes(),
            cfg.validators[1].0.as_bytes()
        );
        assert_eq!(
            loaded.proposal.expect("proposal key").public_key.as_bytes(),
            cfg.validators[1].1.as_bytes()
        );

        let again = write_bundle(dir.path(), spec(1_800_000_000), &mut |_, _| {
            Err("keys must be reused".into())
        })
        .unwrap();
        assert_eq!(again.generated_keys, 0);
        let cfg = ethean_genesis::load_lean_network_config(&again.config).unwrap();
        assert_eq!(cfg.genesis_time, 1_800_000_000);
        assert_eq!(again.nodes[0].node_key, first.nodes[0].node_key);
        assert_eq!(again.nodes[0].multiaddr, first.nodes[0].multiaddr);
        assert_eq!(calls, 6);
    }

    #[test]
    fn empty_or_overflowing_devnets_are_refused() {
        let dir = tempfile::tempdir().unwrap();
        let mut never = |_: u64, _: KeyRole| -> Result<SecretKeyMaterial, String> {
            unreachable!("no key is generated for a refused spec")
        };
        let empty = DevnetSpec {
            nodes: 0,
            ..spec(1)
        };
        assert!(write_bundle(dir.path(), empty, &mut never).is_err());
        let overflow = DevnetSpec {
            base_port: u16::MAX,
            ..spec(1)
        };
        assert!(write_bundle(dir.path(), overflow, &mut never).is_err());
    }
}
