{
 "title": "Lean Ethereum Client Interop (leanMetrics)",
 "tags": [ "interop" ],
 "time": { "from": "2026-03-13T14:47:00.000Z", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": { "query": "label_values(network)" } },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage (%)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (network,instance) (rate(node_cpu_seconds_total{network=~\"$network\", instance=~\"$instance\", mode!=\"idle\"}[2m]))\n  /\n  sum by (network,instance) (rate(node_cpu_seconds_total{network=~\"$network\", instance=~\"$instance\"}[2m]))\n) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg by (instance) (node_memory_MemAvailable_bytes{network=~\"$network\", instance=~\"$instance\"}) / avg by (instance) (node_memory_MemTotal_bytes{network=~\"$network\", instance=~\"$instance\"})) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg by (instance) (node_filesystem_avail_bytes{network=~\"$network\", instance=~\"$instance\", mountpoint=\"/\", fstype!=\"rootfs\"}) / avg by (instance) (node_filesystem_size_bytes{network=~\"$network\", instance=~\"$instance\", mountpoint=\"/\"})) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Clients Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Clients images",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max by (job, name, image, network, container_label_org_opencontainers_image_created, container_label_org_opencontainers_image_revision, container_label_org_opencontainers_image_ref_name)(container_start_time_seconds{job=\"cadvisor\", network=~\"$network\", name=~\"ethlambda.*|grandine.*|lantern.*|lighthouse.*|qlean.*|ream.*|zeam.*|gean.*|nlean.*|peam.*\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "last_over_time(lean_node_info{job=~\"$job\",instance=~\"$instance\",network=~\"$network\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Network start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lean_genesis_time{job=\"lean-quickstart\",network=~\"$network\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "targets": [
    {
     "expr": "sum by(network) (lean_validators_count{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of attestation committees",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "max(lean_attestation_committee_count{network=~\"$network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aggregators",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "max by(network,job,instance) (lean_is_aggregator{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}) > 0",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Validators  list",
   "type": "piechart",
   "description": "Number of validators attached to each node",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (lean_validators_count{network=~\"$network\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (network,job) (lean_validators_count{job=~\"$job\",network=~\"$network\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Latest finalized slot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max(lean_latest_finalized_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest justified slot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
   "targets": [
    {
     "expr": "max(lean_latest_justified_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Head slot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "max(lean_head_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Latest finalized slot",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (network,job,instance)(lean_latest_finalized_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Latest justified slot",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 28 },
   "targets": [
    {
     "expr": " sum by (network,job,instance) (lean_latest_justified_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Head slot",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": " sum by (network,job,instance) (lean_head_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Current slot",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 28 },
   "targets": [
    {
     "expr": " sum by (network,job,instance) (lean_current_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "timeseries",
   "description": "Total number of processed slots in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "changes(lean_node_start_time_seconds{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Attestation committee subnet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum by (network,job,instance) (lean_attestation_committee_subnet{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Connected peers per node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": " sum by (network,instance, job) (lean_connected_peers{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Node sync status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "max by (network, job, instance) (\n  (lean_node_sync_status{status=\"synced\", network=~\"$network\", job=~\"$job\", instance=~\"$instance\"} == 1) * 2\n  or\n  (lean_node_sync_status{status=\"syncing\", network=~\"$network\", job=~\"$job\", instance=~\"$instance\"} == 1) * 1\n  or\n  (lean_node_sync_status{status=\"idle\", network=~\"$network\", job=~\"$job\", instance=~\"$instance\"} == 1) * 0\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Finalizations - Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job,network,instance) (increase(lean_finalizations_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\",result=\"success\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Finalizations - Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job,network,instance) (increase(lean_finalizations_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\",result=\"error\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Finalization/Justification Delay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 }
  },
  {
   "title": "Head - Finalized  delay (slots)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "avg_over_time(lean_head_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[5m]) - avg_over_time(lean_latest_finalized_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Head - Justified delay (slots)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 67 },
   "targets": [
    {
     "expr": "avg_over_time(lean_head_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[5m]) - avg_over_time(lean_latest_justified_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Justified - Finalized  delay (slots)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 67 },
   "targets": [
    {
     "expr": "avg_over_time(lean_latest_justified_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[5m]) - avg_over_time(lean_latest_finalized_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Connected peers per node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": " sum by (job,network,instance) (lean_connected_peers{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Connected peers per node (detailed)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": " sum by (job, client,instance,network) (lean_connected_peers{network=~\"$network\", job=~\"$job\", instance=~\"$instance\", client!=\"\"})",
     "legendFormat": "{{job}} - {{client}}"
    }
   ]
  },
  {
   "title": "Peer connection events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "sum by (job,network,instance) (\n    increase(lean_peer_connection_events_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  {
   "title": "Peer disconnection events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "sum by (job,network,instance) (\n    increase(lean_peer_disconnection_events_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  { "title": "PQ Signatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Total number of attestation signatures",
   "type": "timeseries",
   "description": "Total number of individual attestation signatures",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job,network,instance) (\n    increase(lean_pq_sig_attestation_signatures_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of valid attestation signatures",
   "type": "timeseries",
   "description": "Total number of valid individual attestation signatures",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 97 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job,network,instance) (\n    increase(lean_pq_sig_attestation_signatures_valid_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of invalid attestation signatures",
   "type": "timeseries",
   "description": "Total number of invalid individual attestation signatures",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 97 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job,network,instance) (\n    increase(lean_pq_sig_attestation_signatures_invalid_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to sign an attestation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (rate(lean_pq_sig_attestation_signing_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to verify an attestation signature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (rate(lean_pq_sig_attestation_verification_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of aggregated signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (\n    increase(lean_pq_sig_aggregated_signatures_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of attestations included into aggregated signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job,network,instance) (\n    increase(lean_pq_sig_attestations_in_aggregated_signatures_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of valid aggregated signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job,network,instance) (\n    increase(lean_pq_sig_aggregated_signatures_valid_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of invalid aggregated signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job,network,instance) (\n    increase(lean_pq_sig_aggregated_signatures_invalid_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to build an aggregated signature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (rate(lean_pq_sig_aggregated_signatures_building_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to verify an aggregated signature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (rate(lean_pq_sig_aggregated_signatures_verification_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Fork-Choice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 } },
  {
   "title": "Block processing time",
   "type": "timeseries",
   "description": "Time taken to process block in fork-choice",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_fork_choice_block_processing_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to aggregate committee signatures",
   "type": "timeseries",
   "description": "Time taken to process block in fork-choice",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_committee_signatures_aggregation_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of fork choice reorgs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
   "targets": [
    {
     "expr": "sum by (job) (\n  increase(lean_fork_choice_reorgs_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  {
   "title": "Depth of fork choice reorgs (in blocks)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
   "targets": [
    {
     "expr": "sum by (job) (\n  increase(lean_fork_choice_reorg_depth_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  {
   "title": "Number of gossip signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 154 },
   "targets": [
    {
     "expr": " avg_over_time (\n  sum by (job,network,instance) (\n    (lean_gossip_signatures{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})\n  )[2m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of new aggregated payloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 154 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job,network,instance) (\n   (lean_latest_new_aggregated_payloads{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})\n  )[2m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of known aggregated payloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 154 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job,network,instance) (\n   (lean_latest_known_aggregated_payloads{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})\n  )[1m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Attestations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 } },
  {
   "title": "FC Valid attestations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 163 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job,network,instance) (\n    increase(lean_attestations_valid_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  {
   "title": "FC Invalid attestations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 163 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job,network,instance) (increase(lean_attestations_invalid_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  {
   "title": "FC Attestations validation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(lean_attestation_validation_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Safe target slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 171 },
   "targets": [
    {
     "expr": " sum by (job,network,instance) (lean_safe_target_slot{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "STF Processed attestations",
   "type": "timeseries",
   "description": "Total number of attestations processed in state transition function",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 171 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job,network,instance) (increase(lean_state_transition_attestations_processed_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "STF Attestations processing time",
   "type": "timeseries",
   "description": "Time taken to process attestations in state transition function",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n rate(lean_state_transition_attestations_processing_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to produce attestations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(lean_attestations_production_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{source}}"
    }
   ]
  },
  {
   "title": "Time taken to aggregate committee signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(lean_committee_signatures_aggregation_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "State Transition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 187 } },
  {
   "title": "State transition time",
   "type": "timeseries",
   "description": "Time taken to process state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_state_transition_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block processing time",
   "type": "timeseries",
   "description": "Time taken to process block in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_state_transition_block_processing_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Processed slots",
   "type": "timeseries",
   "description": "Total number of processed slots in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 196 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job,network,instance) (increase(lean_state_transition_slots_processed_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Slots processing time",
   "type": "timeseries",
   "description": "Time taken to process slots in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n rate(lean_state_transition_slots_processing_time_seconds_bucket{network=~\"$network\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Finalizations - Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 204 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job,network,instance) (increase(lean_finalizations_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\",result=\"success\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Finalizations - Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 204 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job,network,instance) (increase(lean_finalizations_total{network=~\"$network\", job=~\"$job\", instance=~\"$instance\",result=\"error\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}